kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
#    kubeadmConfigPatches:
#      - |
#        kind: ClusterConfiguration
#        apiServer:
#          extraArgs:
#            audit-log-path: /var/log/kubernetes/audit.log
#            audit-log-maxage: "30"
#            audit-log-maxbackup: "10"
#            audit-log-maxsize: "100"
#            audit-policy-file: /etc/kubernetes/audit-policy.yaml
#            admission-control-config-file: /etc/kubernetes/admission-control.yaml
#      - |
#        kind: InitConfiguration
#        nodeRegistration:
#          kubeletExtraArgs:
#            node-labels: "ingress-ready=true"

#    extraMounts:
#      - hostPath: D:/MakeIntellex/Projects/mycelisai/scratch/ops/audit-policy.yaml
#        containerPath: /etc/kubernetes/audit-policy.yaml
#        readOnly: true
#      - hostPath: D:/MakeIntellex/Projects/mycelisai/scratch/ops/admission-control.yaml
#        containerPath: /etc/kubernetes/admission-control.yaml
#        readOnly: true
#      - hostPath: D:/MakeIntellex/Projects/mycelisai/scratch/logs/audit
#        containerPath: /var/log/kubernetes
#        readOnly: false
#    extraPortMappings:
#      - containerPort: 80
#        hostPort: 80
#        protocol: TCP
#      - containerPort: 443
#        hostPort: 443
#        protocol: TCP
