apiVersion: v2
name: mycelis-core
description: The Neural Core of Project Mycelis
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: nats
    version: 1.2.4
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
