apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secret
  labels:
    app: postgresql
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  postgres-user: {{ .Values.postgresql.auth.username | b64enc | quote }}
  postgres-db: {{ .Values.postgresql.auth.database | b64enc | quote }}
